// Meldet alle Bausteine an; ohne diese Datei kennt die Maske keinen.
import './button/ButtonBlock'
import './card/CardBlock'
import './datum/Datum'
import './erfassung/Erfassung'
import './formfeld/FormFeld'
import './kanban/KanbanBlock'
import './kanban/KanbanSpalteBlock'
import './kanban/KanbanZimmerBlock'
import './popup/PopupBlock'
import './tabelle/Tabelle'
import './text/Text'
import './trenner/TrennerBlock'
