// Meldet alle Bausteine an; ohne diese Datei kennt die Maske keinen.
import './ansicht/AnsichtBlock'
import './button/ButtonBlock'
import './card/CardBlock'
import './datum/DatumBlock'
import './erfassung/ErfassungBlock'
import './formfeld/FormFeldBlock'
import './kanban/KanbanBlock'
import './kanban/KanbanSpalteBlock'
import './kanban/KanbanZimmerBlock'
import './navi/NaviBlock'
import './navi/NaviEintragBlock'
import './popup/PopupBlock'
import './tabelle/TabelleBlock'
import './text/TextBlock'
import './trenner/TrennerBlock'
